// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaSdPc5bfAxS7UdN5_Iw5oNkz9vcmecc',
    appId: '1:293090097617:web:b23183658c79c6558e08f0',
    messagingSenderId: '293090097617',
    projectId: 'supermarket-app-51515',
    authDomain: 'supermarket-app-51515.firebaseapp.com',
    storageBucket: 'supermarket-app-51515.firebasestorage.app',
    measurementId: 'G-KVFYW8JX2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNiN9zTsiep0fbfn4r7KlPyOg4RSAPaQ',
    appId: '1:293090097617:android:d0fffde66ab01ade8e08f0',
    messagingSenderId: '293090097617',
    projectId: 'supermarket-app-51515',
    storageBucket: 'supermarket-app-51515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZMZJI7zgAAgmuOuAGs-B9didqc2_TEM',
    appId: '1:293090097617:ios:7945f6c8aa2aeda18e08f0',
    messagingSenderId: '293090097617',
    projectId: 'supermarket-app-51515',
    storageBucket: 'supermarket-app-51515.firebasestorage.app',
    iosBundleId: 'com.example.supermarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZMZJI7zgAAgmuOuAGs-B9didqc2_TEM',
    appId: '1:293090097617:ios:7945f6c8aa2aeda18e08f0',
    messagingSenderId: '293090097617',
    projectId: 'supermarket-app-51515',
    storageBucket: 'supermarket-app-51515.firebasestorage.app',
    iosBundleId: 'com.example.supermarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGaSdPc5bfAxS7UdN5_Iw5oNkz9vcmecc',
    appId: '1:293090097617:web:69b4e05080bf30f68e08f0',
    messagingSenderId: '293090097617',
    projectId: 'supermarket-app-51515',
    authDomain: 'supermarket-app-51515.firebaseapp.com',
    storageBucket: 'supermarket-app-51515.firebasestorage.app',
    measurementId: 'G-X3STDVHVBB',
  );
}
